services:
  my-db:
    image: mysql
    container_name: mysql-container
    ports:
        - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dbjwt
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
        - my-jwt-network
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

  my-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: jwtproject
    container_name: jwt-container
    ports:
        - "8081:8081"
    networks:
      - my-jwt-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://my-db:3306/dbjwt
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      my-db:
        condition: service_healthy
networks:
  my-jwt-network:
volumes:
  mysql-data:
